version: '3'
services:
    reader:
        image: openslides-datastore-reader-dev
        volumes:
            - ./shared/shared:/app/shared
            - ./reader/reader:/app/reader
            - ./reader/tests:/app/tests
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        depends_on:
            - postgresql
        networks:
            - postgresql
    writer:
        image: openslides-datastore-writer-dev
        volumes:
            - ./shared/shared:/app/shared
            - ./writer/writer:/app/writer
            - ./writer/tests:/app/tests
            - ./cli:/app/cli
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        networks:
            - redis
networks:
    postgresql:
    redis: