version: '3'
services:
    reader:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                REPOSITORY_URL: "https://github.com/jsangmeister/openslides-datastore-service.git"
                GIT_CHECKOUT: "${OPENSLIDES_DATASTORE_SERVICE_COMMIT_HASH}"
                MODULE: "reader"
                PORT: "${OPENSLIDES_DATASTORE_READER_PORT}"
        image: openslides-datastore-reader
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        depends_on:
            - postgresql
        env_file: settings.env
        environment:
            - DATASTORE_DATABASE_PORT=${DATASTORE_DATABASE_PORT}
        networks:
            - postgresql
    writer:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                REPOSITORY_URL: "https://github.com/jsangmeister/openslides-datastore-service.git"
                GIT_CHECKOUT: "${OPENSLIDES_DATASTORE_SERVICE_COMMIT_HASH}"
                MODULE: "writer"
                PORT: "${OPENSLIDES_DATASTORE_WRITER_PORT}"
                USE_REDIS: "1"
        image: openslides-datastore-writer
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        depends_on:
            - postgresql
            - redis
        env_file: settings.env
        environment:
            - DATASTORE_DATABASE_PORT=${DATASTORE_DATABASE_PORT}
            - MESSAGE_BUS_PORT=${MESSAGE_BUS_PORT}
        networks:
            - postgresql
            - redis
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        environment:
            - DB_USER=openslides
            - DB_PASS=openslides
            - DB_NAME=openslides
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "${MESSAGE_BUS_PORT}:${MESSAGE_BUS_PORT}"
        networks:
            - redis
networks:
    postgresql:
    redis:
