version: '3'
services:
    reader:
        image: openslides-datastore-reader
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_READER_PORT}
            - NUM_WORKERS=8
        depends_on:
            - postgresql
        networks:
            - postgresql
    writer:
        image: openslides-datastore-writer
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_WRITER_PORT}
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgresql:
    redis:
