version: '3'
services:
    reader:
        image: openslides-datastore-reader
        ports:
            - "8001:8001"
        depends_on:
            - postgresql
        networks:
            - postgresql
    writer:
        image: openslides-datastore-writer
        ports:
            - "8000:8000"
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgresql:
    redis:
