version: '3'
services:
    writer:
        image: openslides-datastore-writer-test
        command: ["sleep", "infinity"]
        volumes:
            - ./shared/shared:/app/shared
            - ./writer/writer:/app/writer
            - ./writer/tests:/app/tests
            - ./cli:/app/cli
        depends_on:
            - postgresql
            - redis
        env_file: settings.env
        networks:
            - postgresql
            - redis
    shared:
        image: openslides-datastore-shared-test
        command: ["sleep", "infinity"]
        volumes:
            - ./shared/shared:/app/shared
            - ./shared/tests:/app/tests
        env_file: settings.env
    reader:
        image: openslides-datastore-reader-test
        command: ["sleep", "infinity"]
        volumes:
            - ./shared/shared:/app/shared
            - ./reader/reader:/app/reader
            - ./reader/tests:/app/tests
        depends_on:
            - postgresql
        env_file: settings.env
        networks:
            - postgresql
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        environment:
            - DB_USER=openslides
            - DB_PASS=openslides
            - DB_NAME=openslides
        networks:
            - postgresql
    redis:
        image: redis:alpine
        networks:
            - redis
networks:
    postgresql:
    redis: