version: '3'
services:
    reader:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                REPOSITORY_URL: "https://github.com/OpenSlides/openslides-datastore-service.git"
                GIT_CHECKOUT: "${OPENSLIDES_DATASTORE_SERVICE_GIT_CHECKOUT}"
                MODULE: "reader"
                PORT: "${OPENSLIDES_DATASTORE_READER_PORT}"
        image: openslides-datastore-reader
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        depends_on:
            - postgresql
        networks:
            - postgresql
    writer:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                REPOSITORY_URL: "https://github.com/OpenSlides/openslides-datastore-service.git"
                GIT_CHECKOUT: "${OPENSLIDES_DATASTORE_SERVICE_GIT_CHECKOUT}"
                MODULE: "writer"
                PORT: "${OPENSLIDES_DATASTORE_WRITER_PORT}"
        image: openslides-datastore-writer
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: postgres:11
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "${MESSAGE_BUS_PORT}:${MESSAGE_BUS_PORT}"
        networks:
            - redis
networks:
    postgresql:
    redis:
